print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/hosoji/Documents/Unity/GrafightFolder/Grafight/Assets/Models/topModel.ma"`)
{		
	file -o "/Users/hosoji/Documents/Unity/GrafightFolder/Grafight/Assets/Models/topModel.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/hosoji/Documents/Unity/GrafightFolder/Grafight/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/hosoji/Documents/Unity/GrafightFolder/Grafight/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/hosoji/Documents/Unity/GrafightFolder/Grafight/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
